### ISSUE TITLE
Trigger when "Dual-Audio" in file name

### ISSUE THREAD

**Issue by eiden2233** [po5/trackselect#1]
Edited from you mpv.conf

`profile-cond=string.match(string.lower(string.gsub(require "mp.utils".join_path(get("working-directory", ""), get("path", "")), string.gsub(get("filename", ""), "([^%w])", "%%%1").."$", "")), "dual-audio")~=nil
`

How do I get the script to trigger when dual-audio is in the file name but not the folder?

**Comment by po5** [comment]
Simple match on filename, you don't need all this stuff.  
This is only this messy to support detection of the dir name even when mpv is given a relative path.

**Comment by eiden2233** [comment]
I see, was confused at what it was as I barely have any experience in coding. 

From other profile-cond, I guessed  adding ` or string.match(get("filename", ""), "dual-audio")==nil`  but that made the profile trigger even without dual-audio.

How do I make it so that it detects at least 2 folders down and filename?

**Comment by po5** [comment]
Please refer to the mpv documentation. https://mpv.io/manual/master/#conditional-auto-profiles
