### ISSUE TITLE
Small issue with configuration

### ISSUE THREAD

**Issue by Obegg** [po5/trackselect#3]
I've noticed that on some YouTube videos (example: https://www.youtube.com/watch?v=HAzZH6wccew ) mpv doesn't auto-select `English` as the subtitles, but instead defaults to the first subtitle available (`sid=1`),
So at first I opened an issue (question) on mpv github - https://github.com/mpv-player/mpv/issues/11972
Which did helped and solved the issue,
but now using [trackselect.lua](https://github.com/po5/trackselect/blob/master/trackselect.lua) it doesn't work anymore,
so I guess my configuration of the script is wrong?

`trackselect.conf`:

```
preferred_audio_lang=jpn/en
preferred_audio_channels=8/7/6/5/4/3/2/1
excluded_audio_words=
expected_audio_words=

preferred_sub_lang=en
excluded_sub_words=sign/sdh
expected_sub_words=
```

`mpv.conf`:
```
alang=jpn,en
slang=en
subs-with-matching-audio=yes
```

**Comment by po5** [comment]
YouTube subtitles are marked as external, and we currently short-circuit selection on the first external track encountered.  
The intention was to select external tracks over internal ones, but we should still compute scores for additional external tracks.  
I fixed this, thanks for the report.
